In [1]:
# Load numpy as np
import numpy as np
print "numpy version: ", np.__version__
import sys
print sys.version

numpy version:  1.9.2
2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Dec 18 2014, 16:57:52) [MSC v.1500 64 bit (AMD64)]


In [6]:
# make a numpy array
npa = np.arange(1,201)
print npa

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200]


In [8]:
# some numpy array methods
print "Mean: ",npa.mean()
print "Standard deviation: ",npa.std()
print "Sum: ",npa.sum()
print "Minimum: ", npa.min()
print "Maximum: ", npa.max()

Mean:  100.5
Standard deviation:  57.7343052266
Sum:  20100
Minimum:  1
Maximum:  200


In [56]:
# square all values
npa **2

array([    0,     1,     4,     9,    16,    25,    36,    49,    64,
          81,   100,   121,   144,   169,   196,   225,   256,   289,
         324,   361,   400,   441,   484,   529,   576,   625,   676,
         729,   784,   841,   900,   961,  1024,  1089,  1156,  1225,
        1296,  1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,
        2025,  2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,
        2916,  3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,
        3969,  4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,
        5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,
        6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
        8100,  8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,
        9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449,
       11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456,
       13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625,
       15876, 16129,

In [11]:
# Check if number is divisible by 2
print "Here it is method 1: ", [x for x in npa if x % 2 ==0] #List comprehension
print
print "Here it is method 2: ",filter (lambda x: x% 2 ==0, npa)
print
print "Here it is method 3: ",npa[npa % 2==0] # numpy Boolean to check if number is divisible by 2

Here it is method 1:  [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]

Here it is method 2:  [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]

Here it is method 3:  [  2   4   6   8  10  12  14  16  18

In [12]:
# Boolean to Find all values > 10
print "Here it is: ",npa[npa >10] # numpy 

Here it is:  [ 11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46
  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64
  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82
  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100
 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154
 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190
 191 192 193 194 195 196 197 198 199 200]


In [65]:
# Boolean to Find all values > 15 or less than 5
print "Here it is: ",npa[(npa > 15)|(npa < 5)] # numpy 

Here it is:  [  0   1   2   3   4  16  17  18  19  20  21  22  23  24  25  26  27  28
  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46
  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64
  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82
  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100
 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154
 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190
 191 192 193 194 195 196 197 198 199]


In [66]:
# Make an array of integres
np.array(range(20))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
# Floats
np.array([1.5,4,5,3.14])

array([ 1.5 ,  4.  ,  5.  ,  3.14])

In [15]:
np2=np.array(range(25))
print np2

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [16]:
np3 = np.random.random_integers(0,50,20)
print np3

[10 49 43 32  8 26 46 33 48 37 23 35 31 28 38 45 15  8 16 15]


In [74]:
# Ways to multiple each element 
map(lambda x: x*2,np3)

[70, 28, 36, 14, 98, 94, 60, 34, 68, 8, 92, 30, 38, 64, 96, 32, 36, 22, 38, 84]

In [76]:
# Ways to multiple each element by 2
[x * 2 for x in np3] # List comprehension

[70, 28, 36, 14, 98, 94, 60, 34, 68, 8, 92, 30, 38, 64, 96, 32, 36, 22, 38, 84]

In [77]:
np3*2

array([70, 28, 36, 14, 98, 94, 60, 34, 68,  8, 92, 30, 38, 64, 96, 32, 36,
       22, 38, 84])